### ISSUE TITLE
Is it ok for you if I create a ansible role to install...

### ISSUE THREAD

**Issue by DirectorSloan** [treydock/gpfs_exporter#51]
First at all. Thanks for writing a go gpfs_exporter. We just start enjoy using it. To install it we use ansible. And I wonder if I may contribute the ansible to galaxy via our github Org. https://github.com/Helmholtz-UFZ. This role would be based on your binary releases and systemd, sudo and user creation snippets. Is that ok for you? I will of course mention you as often as possible.

**Comment by treydock** [comment]
That's fine by me.
