### ISSUE TITLE
Add option to replace sudo with dzdo

### ISSUE THREAD

**Issue by richardwcollins** [treydock/gpfs_exporter#53]
Authentication and privilege escalation is managed through Centrify on particular site, which uses dzdo instead of sudo. We have successfully enabled dzdo for all `/usr/lpp/mmfs/bin/*` commands using a policy for a specific user.

Is it possible to add a config option to set dzdo as the execCommand prefix - or is there an alternative approach to force execCommand to use dzdo?

**Comment by treydock** [comment]
Would something like this work?

```
--config.sudo.command=dzdo
```

That would just make it so instead of doing `sudo /usr/lpp/mmfs/bin/mmgetstate -Y` you'd get `dzdo /usr/lpp/mmfs/bin/mmgetstate -Y`.

**Comment by richardwcollins** [comment]
Yes - that would work perfectly well. Thanks for picking this up
