### ISSUE TITLE
Add possibility to run mmlsqos command

### ISSUE THREAD

**Issue by Dmitry099** [treydock/gpfs_exporter#57]
Good day!
This library is really useful for generating GPFS metrics. However, we want to generate additional metrics from the output of mmlsqos command, which isn't included here.
So, I've created PR with my implementation to reach this goal -> https://github.com/treydock/gpfs_exporter/pull/56
Could you please look at it when you'll have time?
P.S. I've already tested it in my dev environment and it works as expected.

**Comment by treydock** [comment]
Closed via #56
