### ISSUE TITLE
Basic Auth and TLS support

### ISSUE THREAD

**Issue by mahendrapaipuri** [treydock/gpfs_exporter#64]
Hello,

Thanks a lot for this great piece of work. Would you be willing to maintain if I submit a PR to add support for basic auth and TLS for the exporter using [exporter toolkit](https://github.com/prometheus/exporter-toolkit)? 

Our security team would like to have some auth as all these commands are available only for `root` by default.

Cheers!!

**Comment by treydock** [comment]
Yep, using the exporter toolkit to do that sounds fine so long as the TLS and auth are all opt-in.

**Comment by mahendrapaipuri** [comment]
Yes, they are totally opt in. Users will have to pass the TLS config file like `gpfs_exporter --web.config.file=web-config.yml` to turn on TLS and/or basic auth. 

Alright. I will try to put up a PR before the end of this week.
